spring:
  application:
    name: marketplace
  datasource:
    url: jdbc:mysql://localhost:3307/TALLT_SoftwareMarket?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

virustotal:
  api-key: fbeee19f2a7b45408e220ff4a07384ff9041af712a50f4fe6eb38b32b3c250b7

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:dwfxvobn3}
  api_key: ${CLOUDINARY_API_KEY:223312713834276}
  api_secret: ${CLOUDINARY_API_SECRET:yG5aXxOkoLXNX2736_2KwJuYpu0}

vnpay:
  tmn-code: 1A1WQ9ZN
  hash-secret: HFWWS0H1PTNNWO8C114AIRI5CR1RA9DP
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8081/api/checkout/vnpay-return
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  version: "2.1.0"
  command: pay
  frontend-url: http://localhost:5173
